### PR TITLE
Move Global values to the top

### PR DESCRIPTION
**Pull request by PatriceJada**

### CODE REVIEW

**Comment by drcandacemakedamoore** [comment]
We will first rebase these changes onto develop, then pull them to the next version of main. Thank you very much!

**Comment by drcandacemakedamoore** [comment]
This was actually a nice change (it will probably move from develop to main today). You have done a few nice changes. We hope to publish in JOSS, do you want to be added as an author? If so please get in touch with me ASAP via this pull request with the required author information i.e. name and institution as they would be on the paper (see the paper).

**Comment by drcandacemakedamoore** [comment]
All done.

**Comment by PatriceJada** [comment]
Yes, thank you. Patrice J Musoke, Temple University, 0000-0002-8379-5130

**Pull request closed without merging**
